
import sys

if len(sys.argv)==2:
	search_string = sys.argv[1]
	print(f"Github scraped for \"{search_string}\"")
	print("\n**Credentials and Secrets**")
	print(f" credentials")
	print(f"https://github.com/search?q=%22{search_string}%22+credentials&type=Code")
	print(f"  password")	
	print(f"https://github.com/search?q=%22{search_string}%22+password&type=Code")
	print(f" bashrc password")
	print(f"https://github.com/search?q=%22{search_string}%22+bashrc%20password&type=Code")
	print(f" .bash_history")
	print(f"https://github.com/search?q=%22{search_string}%22+.bash_history&type=Code")
	print(f" npmrc _auth")
	print(f"https://github.com/search?q=%22{search_string}%22+npmrc%20_auth&type=Code")	
	print(f" htpasswd")
	print(f"https://github.com/search?q=%22{search_string}%22+htpasswd&type=Code")
	print(f" git-credentials")
	print(f"https://github.com/search?q=%22{search_string}%22+git-credentials&type=Code")
	print(f"  id_rsa")
	print(f"https://github.com/search?q=%22{search_string}%22+id_rsa&type=Code")
	print(f"  passwd")
	print(f"https://github.com/search?q=%22{search_string}%22+passwd&type=Code")
	print(f" secrets")
	print(f"https://github.com/search?q=%22{search_string}%22+secrets&type=Code")
	print(f"  SECRET_KEY")
	print(f"https://github.com/search?q=%22{search_string}%22+SECRET_KEY&type=Code")
	print(f" client_secret")
	print(f"https://github.com/search?q=%22{search_string}%22+client_secret&type=Code")
	print(f"  api_key")
	print(f"https://github.com/search?q=%22{search_string}%22+api_key&type=Code")
	print(f" aws_access_key_id")
	print(f"https://github.com/search?q=%22{search_string}%22+aws_access_key_id&type=Code")
	print(f" xoxp OR xoxb OR xoxa")
	print(f"https://github.com/search?q=%22{search_string}%22+xoxp%20OR%20xoxb&type=Code")
	print(f" github_token")
	print(f"https://github.com/search?q=%22{search_string}%22+github_token&type=Code")
	print(f" app_secret")
	print(f"https://github.com/search?q=%22{search_string}%22+app_secret&type=Code")
	
	print("\n**Configs and misc.**")
	print(f" dockercfg")
	print(f"https://github.com/search?q=%22{search_string}%22+dockercfg&type=Code")
	print(f"  pem private")
	print(f"https://github.com/search?q=%22{search_string}%22+extension:pem%20private&type=Code")
	print(f"  s3cfg")
	print(f"https://github.com/search?q=%22{search_string}%22+s3cfg&type=Code")
	print(f" sshd_config")
	print(f"https://github.com/search?q=%22{search_string}%22+sshd_config&type=Code")	
	print(f" sshd_config")
	print(f"https://github.com/search?q=%22{search_string}%22+sshd_config&type=Code")
	print(f" FTP")
	print(f"https://github.com/search?q=%22{search_string}%22+FTP&type=Code")
	print(f" s3.yml")
	print(f"https://github.com/search?q=%22{search_string}%22+.env&type=Code")
	print(f" .exs")
	print(f"https://github.com/search?q=%22{search_string}%22+.exs&type=Code")
	print(f" beanstalkd.yml")
	print(f"https://github.com/search?q=%22{search_string}%22+beanstalkd.yml&type=Code")
	print(f" deploy.rake")
	print(f"https://github.com/search?q=%22{search_string}%22+deploy.rake&type=Code")
	print(f" mysql")
	print(f"https://github.com/search?q=%22{search_string}%22+mysql&type=Code")
	print(f"  PWD")
	print(f"https://github.com/search?q=%22{search_string}%22+PWD&type=Code")
	print(f" deploy.rake")
	print(f"https://github.com/search?q=%22{search_string}%22+deploy.rake&type=Code")
	print(f" .sls")
	print(f"https://github.com/search?q=%22{search_string}%22+PWD&type=Code")
	print(f" composer.json")
	print(f"https://github.com/search?q=%22{search_string}%22+composer.json&type=Code")
else:
	print("To use: \"python3 git_dorked.py <search>\"")


